// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://localhost:8000',
  defaultLanguage: 'pt-BR',
  supportedLanguages: [
    'pt-BR',
    'en-US',
  ]
};
